name: app
description: Ứng dụng quét, tạo qrcode nội dung động CodeCraft

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  go_router: ^16.0.0

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  jwt_decode: ^0.3.1
  connectivity_plus: ^6.1.4
  hive: ^2.2.3
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_keyboard_visibility: ^6.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  file: ^7.0.1
  url_strategy: ^0.3.0
  flutter_portal: ^1.1.4
  dotted_border: ^3.1.0
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  sentry_flutter: ^9.4.1
  
  # Authentication
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1

  internal_core:
    git:
      url: https://github.com/mminhlequang/internal_libs_flutter.git
      path: core/
      ref: 37ea161d815f7c95088f8a2e918f2ae793ade15c
  internal_network:
    git:
      url: https://github.com/mminhlequang/internal_libs_flutter.git
      path: network/
      ref: 37ea161d815f7c95088f8a2e918f2ae793ade15c


dependency_overrides:
  http: ^1.3.0
  intl: ^0.20.2
  js: ^0.7.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_lints: ^6.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
